version: "3"

services:

  mariadb:
    image: uselagoon/mariadb-10.5-drupal
    ports:
      - "3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MARIADB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 2m
      retries: 20

  drupal:
    image: shipshape-e2e-drupal
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile
    working_dir: /shipshape/tests/e2e/suites
    depends_on:
      mariadb:
        condition: service_healthy
