collect:
  install-profile:
    yaml.key:
      file: config/default/core.extension.yml
      path: profile
  config-files-roles:
    file.lookup:
      path: config/default
      pattern: user.role.*.yml
  role-is-admin:
    yaml.key:
      input: config-files-roles
      path: is_admin
  role-permissions:
    yaml.key:
      input: config-files-roles
      path: permissions

analyse:
  wrong-install-profile:
    not-equal:
      description: Wrong install profile found
      input: install-profile
      value: govcms
  admin-role-found:
    equal:
      description: Admin role found
      input: role-is-admin
      value: true
      severity: high
  disallowed-permissions-found:
    map-list-contain:
      description: Disallowed permissions found
      input: role-permissions
      severity: high
      values:
        - administer config permissions
        - administer modules
        - administer permissions
        - administer seckit
        - administer site configuration
        - administer software updates
        - import configuration
        - synchronize configuration
        - use PHP for google analytics tracking visibility
  anonymous-role-disallowed-permissions-found:
    map-list-contain:
      description: Disallowed permissions found for anonymous role
      input: role-permissions
      key: user.role.anonymous.yml
      values:
        - 'access administration pages'
        - 'access content overview'
        - 'access site reports'
        - 'access user profiles'
        - 'administer account settings'
        - 'administer blocks'
        - 'administer comment types'
        - 'administer comments'
        - 'administer contact forms'
        - 'administer content types'
        - 'administer filters'
        - 'administer image styles'
        - 'administer menu'
        - 'administer nodes'
        - 'administer search'
        - 'administer shortcuts'
        - 'administer taxonomy'
        - 'administer themes'

output:
  stdout:
    format: json
  file:
    path: /results.junit
    format: junit
  lagoon.problems:
    api_key:
    api_endpoint:
